### ISSUE TITLE
Bug: Only works when soundcard is set as the default

### ISSUE THREAD

**Issue by black-ish** [mdonoughe/sbz-switch#1]
When using sbz-switch with a virtual audio cable or in conjunction with other soundcards (multiple wdm output/playback devices) and not having the soundblaster set as the windows default it will throw an error:
``thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: NotSupported', src\libcore\result.rs:906:4
note: Run with `RUST_BACKTRACE=1` for a backtrace.
Jul 16 18:07:33.568 INFO Setting muted to true..., module: sbz_switch::media:163
Jul 16 18:07:33.570 INFO Setting muted to false..., module: sbz_switch::media:163``

It seems that it doesn't try to find the right output (wdm playback device) and only uses the default, which in this case is a virtual audio cable.
Setting the soundcard (soundblaster) as the default will remedy this of course.

**Comment by black-ish** [comment]
Yes that would be enough and a really good solution. Thank you for answering :+1:

**Comment by mdonoughe** [comment]
Try version 2.0.0.

```
PS> sbz-switch list-devices
[[]]
id = '{0.0.0.00000000}.{15769be7-350c-47e0-90d2-c6031d2a6cfa}'
interface = 'Sound Blaster Z'
description = 'Speakers'

[[]]
id = '{0.0.0.00000000}.{435524ef-e50a-49db-82da-2f497744325b}'
interface = 'Steam Streaming Microphone'
description = 'Speakers'

[[]]
id = '{0.0.0.00000000}.{5558cb3d-5ebb-47af-a437-2803acf7eb48}'
interface = 'Steam Streaming Speakers'
description = 'Speakers'

[[]]
id = '{0.0.0.00000000}.{cee1531a-c95a-492a-bca9-a4ca8b3dd5b7}'
interface = '2- USB Audio Device'
description = 'Speakers'
```
```
PS> sbz-switch dump -d '{0.0.0.00000000}.{15769be7-350c-47e0-90d2-c6031d2a6cfa}'
[creative."Bass Management"]
...
```

**Comment by black-ish** [comment]
Tried it and it works beautifully, thank you very much :)
