### ISSUE TITLE
Minor Feature Request: Hide terminal/console window

### ISSUE THREAD

**Issue by black-ish** [mdonoughe/sbz-switch#2]
Just a minor feature request.
When using sbz-switch with a shortcut it opens a terminal/console window for a short time which can be annoying at times.
Could there be just an additional -hide switch be added?

**Comment by mdonoughe** [comment]
Unfortunately that's the way Windows works. Whether the program has a console window or not is determined at compile time so either you get a console window or it's difficult to use the program from a CLI. There are two ways around this.

You can have two executables with the only difference being that one is console subsystem and the other is windows subsystem. To run without a console you run the windows subsystem version. This is why on Windows you have stuff like pythonw and javaw.

You can use a windows subsystem program to launch the console subsystem program. See [Run a batch file in a completely hidden way](https://superuser.com/questions/62525/run-a-batch-file-in-a-completely-hidden-way).

**Comment by black-ish** [comment]
All right, thank you for explaining it.
And thank you for this (sbz-switch) program it helps out tremendously.
